const students = [
  { name: 'abdurrahman hanif alfatih', status: 'LULUS', photo: 'images/abdurrahman_hanif_alfatih.jpg' },
  { name: 'abrar fathir hariyono', status: 'LULUS', photo: 'images/abrar_fathir_hariyono.jpg' },
  { name: 'afiqah putri ayatullah', status: 'LULUS', photo: 'images/afiqah_putri_ayatullah.jpg' },
  { name: 'ahmad waldan syauqi', status: 'LULUS', photo: 'images/ahmad_waldan_syauqi.jpg' },
  { name: 'alzam may fauzan astrolobi', status: 'LULUS', photo: 'images/alzam_may_fauzan_astrolobi.jpg' },
  { name: 'aqilah qothrun nada', status: 'LULUS', photo: 'images/aqilah_qothrun_nada.jpg' },
  { name: 'askana zahra ratifa', status: 'LULUS', photo: 'images/askana_zahra_ratifa.jpg' },
  { name: 'asma hana nadia', status: 'LULUS', photo: 'images/asma_hana_nadia.jpg' },
  { name: 'bilal as saif', status: 'LULUS', photo: 'images/bilal_as_saif.jpg' },
  { name: 'dera alena syahama', status: 'LULUS', photo: 'images/dera_alena_syahama.jpg' },
  { name: 'fahmi izzuddin hasan', status: 'LULUS', photo: 'images/fahmi_izzuddin_hasan.jpg' },
  { name: 'faiza latifa', status: 'LULUS', photo: 'images/faiza_latifa.jpg' },
  { name: 'fathan pramatya', status: 'LULUS', photo: 'images/fathan_pramatya.jpg' },
  { name: 'hana khaira nur fatimah', status: 'LULUS', photo: 'images/hana_khaira_nur_fatimah.jpg' },
  { name: 'hasna raihana', status: 'LULUS', photo: 'images/hasna_raihana.jpg' },
  { name: 'khasyafa aulia azizah', status: 'LULUS', photo: 'images/khasyafa_aulia_azizah.jpg' },
  { name: 'kiagus radithya', status: 'LULUS', photo: 'images/kiagus_radithya.jpg' },
  { name: 'm. faqih ihsan', status: 'LULUS', photo: 'images/m_faqih_ihsan.jpg' },
  { name: 'm. musab al ghofiqi', status: 'LULUS', photo: 'images/m_musab_al_ghofiqi.jpg' },
  { name: 'muhammad arif al-faruq', status: 'LULUS', photo: 'images/muhammad_arif_alfaruq.jpg' },
  { name: 'muhammad hafidz ar rahim', status: 'LULUS', photo: 'images/muhammad_hafidz_ar_rahim.jpg' },
  { name: 'muhammad khalil elshirazy', status: 'LULUS', photo: 'images/muhammad_khalil_elshirazy.jpg' },
  { name: 'muhammad najib arrosyad', status: 'LULUS', photo: 'images/muhammad_najib_arrosyad.jpg' },
  { name: 'ranum ramadhani assyafa', status: 'LULUS', photo: 'images/ranum_ramadhani_assyafa.jpg' },
  { name: 'shofia az zahra', status: 'LULUS', photo: 'images/shofia_az_zahra.jpg' },
  { name: 'syahla ramadhani', status: 'LULUS', photo: 'images/syahla_ramadhani.jpg' },
  { name: 'syahwa ramadhani', status: 'LULUS', photo: 'images/syahwa_ramadhani.jpg' },
  { name: 'yusuf abdur rahman', status: 'LULUS', photo: 'images/yusuf_abdur_rahman.jpg' },
  { name: 'zafreena ainun nida', status: 'LULUS', photo: 'images/zafreena_ainun_nida.jpg' },
];